# Modeling

In the previous codelab session, you cleaned and prepared the quantities of interest in the ESS10 data, relevant to our hypothesis:

> **Centrist individuals exhibit lower levels of affective polarisation.**

In this codelab, we will:

1. Load the preprocessed ESS data
2. Specify and estimate a sequence of linear regression models
3. Compare models to understand how the centrism coefficient changes
4. Interpret the results in relation to our hypothesis
5. Bonus - create a visualization of the results

### Learning Objectives

- Understand how to specify and interpret a **linear regression model** using `statsmodels` (formula API)
- Apply modelling to the ESS dataset by estimating nested models
- Compare models and reflect on potential confounding and robustness

### Tips

- You should adapt code from previous [notebooks](https://github.com/mickaeltemporao/materials/tree/main), mostly from:
    - `07-data-modeling-insights.ipynb`

## Loading the Data

We'll use the preprocessing function we created to load a clean, modelling-ready dataset.

A new function has been added/defined inside `code/preprocess.py` take a look!
- it is called `clean_data`

In [36]:
# Import necessary libraries
import sys
import pandas as pd

# Adding the code directory to path
sys.path.append('../code')

# Import the preprocessing function
from preprocess import clean_data

In [37]:
# Load the preprocessed data
df = clean_data()
df.sample(5)

,agea,clsprty,gndr,hinctnta,lrscale,polintr,prtclffr,prtdgcl,prtvtefr,vote,centrism,affective_polarization,female
13019,85,2,1,10,7,1,66.0,6,7.0,1,0,0.425,0
12182,47,2,1,7,2,4,66.0,6,66.0,2,0,0.825,0
11987,75,1,2,8,6,1,7.0,2,7.0,1,1,0.275,1
13024,66,2,2,5,3,2,66.0,6,5.0,1,0,0.700,1
12828,48,2,2,10,7,3,66.0,6,66.0,2,0,0.800,1

In [38]:
# Check the key variables for our analysis
df.describe()

,agea,clsprty,gndr,hinctnta,lrscale,polintr,prtclffr,prtdgcl,prtvtefr,vote,centrism,affective_polarization,female
count,1564.000000,1564.000000,1564.000000,1564.000000,1564.000000,1564.000000,1564.000000,1564.000000,1564.000000,1564.000000,1564.000000,1564.000000,1564.000000
mean,50.157928,1.581202,1.494885,6.444373,5.050512,2.554987,39.189898,4.358056,36.654092,1.669437,0.494885,0.563251,0.494885
std,17.839011,0.764992,0.500134,2.945893,2.265631,0.960603,29.693816,1.855201,30.668891,1.151954,0.500134,0.183284,0.500134
min,16.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,36.000000,1.000000,1.000000,4.000000,4.000000,2.000000,7.000000,2.000000,7.000000,1.000000,0.000000,0.425000,0.000000
50%,51.000000,2.000000,1.000000,7.000000,5.000000,3.000000,66.000000,6.000000,13.000000,1.000000,0.000000,0.550000,0.000000
75%,64.000000,2.000000,2.000000,9.000000,7.000000,3.000000,66.000000,6.000000,66.000000,2.000000,1.000000,0.700000,1.000000
max,90.000000,8.000000,2.000000,10.000000,10.000000,4.000000,88.000000,6.000000,88.000000,8.000000,1.000000,1.000000,1.000000

## Building Regression Models

Use the **`statsmodels` formula API** to specify regression models. 

```
DV ~ IV + Control_1 + Control_2
```

**Key points:**
- The dependent variable (DV) goes on the left side of the `~`
- Independent variables go on the right side
- Categorical variables should be wrapped in `C()` to ensure proper treatment

Start by loading statsmodels formula api as `sm`.

dv = afffective polarisation

In [39]:
# Import statsmodels formula api 
!pip install statsmodels 
import statsmodels.formula.api as sm

Requirement already satisfied: statsmodels in c:\python314\lib\site-packages (0.14.6)
Requirement already satisfied: numpy<3,>=1.22.3 in c:\python314\lib\site-packages (from statsmodels) (2.3.4)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in c:\python314\lib\site-packages (from statsmodels) (1.17.1)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\python314\lib\site-packages (from statsmodels) (2.3.3)
Requirement already satisfied: patsy>=0.5.6 in c:\python314\lib\site-packages (from statsmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in c:\users\samuelardechois\appdata\roaming\python\python314\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\python314\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\python314\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\python314\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in c:\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

### Model 1: Baseline Model

Our first model is a **baseline** that examines the relationship between centrism and affective polarisation **without any control variables**.

**Task:**
1. Specify a formula with `affective_polarisation` as the DV and `centrism` as the IV
2. Fit the model using `sm.ols()`
3. Print the model summary

In [40]:
# Your code here:
# Define the baseline formula and save it to formula_baseline`
formula_baseline = "affective_polarization ~ centrism"

In [41]:

# Fit the model using the created formula and the prepared dataset
model_baseline = sm.ols(formula=formula_baseline, data=df).fit()
# Print the summary
print(model_baseline.summary())

                              OLS Regression Results
==================================================================================
Dep. Variable:     affective_polarization   R-squared:                       0.001
Model:                                OLS   Adj. R-squared:                  0.000
Method:                     Least Squares   F-statistic:                     1.581
Date:                    Wed, 18 Mar 2026   Prob (F-statistic):              0.209
Time:                            10:42:17   Log-Likelihood:                 435.74
No. Observations:                    1564   AIC:                            -867.5
Df Residuals:                        1562   BIC:                            -856.8
Df Model:                               1
Covariance Type:                nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.5690      0.007     87.276      0.000       0.556       0.582
centrism      -0.0117      0.009     -1.258      0.209      -0.030       0.007
==============================================================================
Omnibus:                       32.706   Durbin-Watson:                   2.024
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               32.050
Skew:                           0.319   Prob(JB):                     1.10e-07
Kurtosis:                       2.710   Cond. No.                         2.61
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### Model 2: Adding Demographic Controls

Now let's add **key demographic controls** to see how the relationship with your DV evolves.

Include:
- **Age** (`agea`)
- **Gender** (`female`)
- **Income** (`hinctnta`)


**Note:** If we had a categorical variable with multiple groups, we'd use `C()`.

**Task:**
1. Extend the formula to include key control variables 
2. Fit the model
3. Print the summary

In [42]:
# Your code here:
# Define formula_controls with key demographic controls
formula_controls = "affective_polarization ~ centrism + agea + female + hinctnta"

# Fit the model using the created formula and the prepared dataset
model_controls = sm.ols(formula=formula_controls, data=df).fit()
# Print the summary
print(model_controls.summary())

                              OLS Regression Results
==================================================================================
Dep. Variable:     affective_polarization   R-squared:                       0.028
Model:                                OLS   Adj. R-squared:                  0.025
Method:                     Least Squares   F-statistic:                     11.19
Date:                    Wed, 18 Mar 2026   Prob (F-statistic):           5.96e-09
Time:                            10:42:18   Log-Likelihood:                 457.08
No. Observations:                    1564   AIC:                            -904.2
Df Residuals:                        1559   BIC:                            -877.4
Df Model:                               4
Covariance Type:                nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.6535      0.020     33.308      0.000       0.615       0.692
centrism      -0.0141      0.009     -1.542      0.123      -0.032       0.004
agea          -0.0003      0.000     -1.127      0.260      -0.001       0.000
female        -0.0042      0.009     -0.453      0.651      -0.022       0.014
hinctnta      -0.0103      0.002     -6.546      0.000      -0.013      -0.007
==============================================================================
Omnibus:                       19.898   Durbin-Watson:                   2.042
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               19.509
Skew:                           0.247   Prob(JB):                     5.80e-05
Kurtosis:                       2.765   Cond. No.                         235.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### Model 3: Fully Specified Model

Finally, let's add other key controls variables that are relevant to our hypothesis:

- **Political interest** (`polintr`)
- **Ideology** (`lrscale`) 

**Task:**
1. Create a formula that includes all previous variables plus `prtclffr` and `lrscale`
2. Fit the model
3. Print the summary

In [43]:
# Your code here:
# Define formula_final with key demographic controls
formula_final = "affective_polarization ~ centrism + agea + female + hinctnta + polintr + lrscale"

# Fit the model using the created formula and the prepared dataset
model_final = sm.ols(formula=formula_final, data=df).fit()
# Print the summary
print(model_final.summary())

                              OLS Regression Results
==================================================================================
Dep. Variable:     affective_polarization   R-squared:                       0.072
Model:                                OLS   Adj. R-squared:                  0.068
Method:                     Least Squares   F-statistic:                     20.01
Date:                    Wed, 18 Mar 2026   Prob (F-statistic):           1.24e-22
Time:                            10:42:18   Log-Likelihood:                 493.03
No. Observations:                    1564   AIC:                            -972.1
Df Residuals:                        1557   BIC:                            -934.6
Df Model:                               6
Covariance Type:                nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.5617      0.026     21.758      0.000       0.511       0.612
centrism      -0.0243      0.009     -2.685      0.007      -0.042      -0.007
agea           0.0001      0.000      0.500      0.617      -0.000       0.001
female        -0.0170      0.009     -1.856      0.064      -0.035       0.001
hinctnta      -0.0073      0.002     -4.633      0.000      -0.010      -0.004
polintr        0.0390      0.005      7.924      0.000       0.029       0.049
lrscale       -0.0073      0.002     -3.656      0.000      -0.011      -0.003
==============================================================================
Omnibus:                       20.202   Durbin-Watson:                   2.044
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               20.704
Skew:                           0.273   Prob(JB):                     3.19e-05
Kurtosis:                       2.862   Cond. No.                         314.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## Comparing Models

Let's compare all three models side-by-side using `summary_col()`.

In [44]:
from statsmodels.iolib.summary2 import summary_col

In [45]:
# Compare the three models
my_models = [model_baseline, model_final, model_baseline]

In [46]:
# Then we use the summary_col() function from the statsmodels package
summary_col(my_models)
# same as 
print(summary_col([model_baseline, model_final, model_baseline]))

============================================================================================
               affective_polarization I affective_polarization II affective_polarization III
--------------------------------------------------------------------------------------------
Intercept      0.5690                   0.5617                    0.5690
               (0.0065)                 (0.0258)                  (0.0065)
centrism       -0.0117                  -0.0243                   -0.0117
               (0.0093)                 (0.0090)                  (0.0093)
agea                                    0.0001
                                        (0.0003)
female                                  -0.0170
                                        (0.0091)
hinctnta                                -0.0073
                                        (0.0016)
polintr                                 0.0390
                                        (0.0049)
lrscale                                 -0.0073
                                        (0.0020)
R-squared      0.0010                   0.0716                    0.0010
R-squared Adj. 0.0004                   0.0680                    0.0004
============================================================================================
Standard errors in parentheses.

In [53]:
print(summary_col([model_baseline, model_final, model_baseline]))

============================================================================================
               affective_polarization I affective_polarization II affective_polarization III
--------------------------------------------------------------------------------------------
Intercept      0.5690                   0.5617                    0.5690
               (0.0065)                 (0.0258)                  (0.0065)
centrism       -0.0117                  -0.0243                   -0.0117
               (0.0093)                 (0.0090)                  (0.0093)
agea                                    0.0001
                                        (0.0003)
female                                  -0.0170
                                        (0.0091)
hinctnta                                -0.0073
                                        (0.0016)
polintr                                 0.0390
                                        (0.0049)
lrscale                                 -0.0073
                                        (0.0020)
R-squared      0.0010                   0.0716                    0.0010
R-squared Adj. 0.0004                   0.0680                    0.0004
============================================================================================
Standard errors in parentheses.

## Interpretation

**Key questions to consider:**

1. **Coefficient stability:** How does the `centrism` coefficient change across models?
2. **Statistical significance:** Is `centrism` statistically significant in all models?
3. **Direction of effect:** Is the coefficient positive or negative? What does this mean for our hypothesis?
4. **Confounding:** Do the demographic controls substantially change the centrism coefficient? What does this suggest?
5. **Model fit:** How does R-squared change as we add controls?

**So What?**
> Do centrist individuals exhibit lower affective polarisation?

Based on the model results, what can we conclude about our hypothesis?

## (Optional) Visualisation

Try creating a publication-ready figure showing the relationship between centrism and affective polarisation. You may use any library you like and seek help (e.g. using online resources or tools such as ChatGPT...) to produce the most effective figure you can. Try to make it look great!

You should explore modern python visualisation libraries.
- avoid using matplotlib, there are many great dataviz libraries out there
    - see https://github.com/gribouille/awesome-python?tab=readme-ov-file#data-visualization

In [49]:
# Your code here
!pip install plotly

Requirement already satisfied: plotly in c:\python314\lib\site-packages (6.6.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\python314\lib\site-packages (from plotly) (2.17.0)
Requirement already satisfied: packaging in c:\users\samuelardechois\appdata\roaming\python\python314\site-packages (from plotly) (25.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip